;;; emacs-solo-icons.el --- File type icon definitions for Emacs Solo  -*- lexical-binding: t; -*-
;;
;; Author: Rahul Martim Juliato
;; URL: https://github.com/LionyxML/emacs-solo
;; Package-Requires: ((emacs "31.1"))
;; Keywords: faces, convenience
;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:
;;
;; Defines file type icon mappings (emoji and nerd-font variants)
;; used by other Emacs Solo features (Dired, eshell, ibuffer).

;;; Code:

(defvar emacs-solo/file-icons
  '(("3gp"            :nerd "" :emoji "🎬")
    ("7z"             :nerd "" :emoji "📦")
    ("Dockerfile"     :nerd "" :emoji "🐋")
    ("apk"            :nerd "" :emoji "📱")
    ("astro"          :nerd "" :emoji "🚀")
    ("aux"            :nerd "" :emoji "📝")
    ("avi"            :nerd "" :emoji "🎬")
    ("azw3"           :nerd "" :emoji "📚")
    ("bak"            :nerd "" :emoji "🗃️")
    ("bash"           :nerd "" :emoji "💻")
    ("bat"            :nerd "" :emoji "⚡")
    ("bbl"            :nerd "" :emoji "📚")
    ("bib"            :nerd "" :emoji "📚")
    ("blg"            :nerd "" :emoji "📝")
    ("bmp"            :nerd "" :emoji "🖼️")
    ("bz2"            :nerd "" :emoji "📦")
    ("c"              :nerd "" :emoji "🅲")
    ("chm"            :nerd "" :emoji "📚")
    ("cls"            :nerd "" :emoji "📚")
    ("conf"           :nerd "" :emoji "⚙️")
    ("config"         :nerd "" :emoji "⚙️")
    ("cpp"            :nerd "" :emoji "🅲")
    ("crt"            :nerd "" :emoji "🔐")
    ("css"            :nerd "" :emoji "🎨")
    ("csv"            :nerd "" :emoji "📊")
    ("cue"            :nerd "" :emoji "📀")
    ("data"           :nerd "" :emoji "📊")
    ("db"             :nerd "" :emoji "🗄️")
    ("deb"            :nerd "" :emoji "📦")
    ("desktop"        :nerd "" :emoji "🖥️")
    ("diff"           :nerd "" :emoji "🔀")
    ("direddir"       :nerd "" :emoji "📁")
    ("diredfile"      :nerd "" :emoji "📄")
    ("dll"            :nerd "" :emoji "🔌")
    ("dmg"            :nerd "" :emoji "💻")
    ("dockerignore"   :nerd "" :emoji "🐋")
    ("dtx"            :nerd "" :emoji "📚")
    ("el"             :nerd "" :emoji "📜")
    ("eld"            :nerd "" :emoji "📜")
    ("env"            :nerd "" :emoji "🔑")
    ("eot"            :nerd "" :emoji "🔠")
    ("epub"           :nerd "" :emoji "📚")
    ("exe"            :nerd "" :emoji "⚡")
    ("fb2"            :nerd "" :emoji "📚")
    ("fish"           :nerd "" :emoji "🐟")
    ("flac"           :nerd "" :emoji "🎶")
    ("flv"            :nerd "" :emoji "🎬")
    ("gif"            :nerd "" :emoji "🖼️")
    ("git"            :nerd "" :emoji "🌱")
    ("gitignore"      :nerd "" :emoji "🌱")
    ("go"             :nerd "" :emoji "🌍")
    ("gpg"            :nerd "" :emoji "🔐")
    ("gradle"         :nerd "" :emoji "🐘")
    ("gz"             :nerd "" :emoji "📦")
    ("h"              :nerd "" :emoji "📘")
    ("hash"           :nerd "" :emoji "#️⃣")
    ("heic"           :nerd "" :emoji "🖼️")
    ("hpp"            :nerd "" :emoji "📘")
    ("html"           :nerd "" :emoji "🌐")
    ("ico"            :nerd "" :emoji "🖼️")
    ("ics"            :nerd "" :emoji "📅")
    ("info"           :nerd "ℹ" :emoji "ℹ️")
    ("ini"            :nerd "" :emoji "⚙️")
    ("ins"            :nerd "" :emoji "📚")
    ("iso"            :nerd "" :emoji "💿")
    ("java"           :nerd "" :emoji "☕")
    ("jpeg"           :nerd "" :emoji "🖼️")
    ("jpg"            :nerd "" :emoji "🖼️")
    ("js"             :nerd "" :emoji "⚙️")
    ("json"           :nerd "" :emoji "🗂️")
    ("jsx"            :nerd "" :emoji "⚙️")
    ("kotlin"         :nerd "" :emoji "🟣")
    ("latex"          :nerd "" :emoji "📚")
    ("lisp"           :nerd "" :emoji "📜")
    ("lock"           :nerd "" :emoji "🔒")
    ("lof"            :nerd "" :emoji "📑")
    ("log"            :nerd "" :emoji "📝")
    ("lot"            :nerd "" :emoji "📑")
    ("lua"            :nerd "" :emoji "🎮")
    ("m4a"            :nerd "" :emoji "🎶")
    ("mail"           :nerd "" :emoji "📧")
    ("makefile"       :nerd "" :emoji "🏗️")
    ("md"             :nerd "" :emoji "📝")
    ("md5"            :nerd "" :emoji "🔐")
    ("mkv"            :nerd "" :emoji "🎬")
    ("mobi"           :nerd "" :emoji "📚")
    ("mov"            :nerd "" :emoji "🎬")
    ("mp3"            :nerd "" :emoji "🎶")
    ("mp4"            :nerd "" :emoji "🎬")
    ("mpg"            :nerd "" :emoji "🎬")
    ("news"           :nerd "" :emoji "📰")
    ("nim"            :nerd "" :emoji "👑")
    ("nix"            :nerd "" :emoji "❄️")
    ("ogg"            :nerd "" :emoji "🎶")
    ("ogv"            :nerd "" :emoji "🎬")
    ("org"            :nerd "" :emoji "🦄")
    ("otf"            :nerd "" :emoji "🔠")
    ("patch"          :nerd "" :emoji "🩹")
    ("pdf"            :nerd "" :emoji "📄")
    ("pem"            :nerd "" :emoji "🔐")
    ("php"            :nerd "" :emoji "🐘")
    ("pl"             :nerd "" :emoji "🐍")
    ("png"            :nerd "" :emoji "🖼️")
    ("ps1"            :nerd "" :emoji "🔧")
    ("psd"            :nerd "" :emoji "🎨")
    ("py"             :nerd "" :emoji "🐍")
    ("r"              :nerd "󰟔" :emoji "📊")
    ("rar"            :nerd "" :emoji "📦")
    ("rb"             :nerd "" :emoji "💎")
    ("rpm"            :nerd "" :emoji "📦")
    ("rs"             :nerd "" :emoji "💨")
    ("sass"           :nerd "" :emoji "🎨")
    ("scheme"         :nerd "" :emoji "📜")
    ("scss"           :nerd "" :emoji "🎨")
    ("sh"             :nerd "" :emoji "💻")
    ("sha256"         :nerd "" :emoji "🔐")
    ("sql"            :nerd "" :emoji "🗄️")
    ("sqlite"         :nerd "" :emoji "🗄️")
    ("srt"            :nerd "" :emoji "🔠")
    ("sty"            :nerd "" :emoji "📚")
    ("svg"            :nerd "" :emoji "🖼️")
    ("swift"          :nerd "" :emoji "🕊️")
    ("tar"            :nerd "" :emoji "📦")
    ("tar.gz"         :nerd "" :emoji "📦")
    ("tar.xz"         :nerd "" :emoji "📦")
    ("tar.zst"        :nerd "" :emoji "📦")
    ("terminal"       :nerd "" :emoji "💻")
    ("tex"            :nerd "" :emoji "📚")
    ("tgz"            :nerd "" :emoji "📦")
    ("tmp"            :nerd "" :emoji "🗄️")
    ("toc"            :nerd "" :emoji "📑")
    ("toml"           :nerd "" :emoji "⚙️")
    ("torrent"        :nerd "" :emoji "🧲")
    ("ts"             :nerd "" :emoji "⚙️")
    ("tsx"            :nerd "" :emoji "⚙️")
    ("ttf"            :nerd "" :emoji "🔠")
    ("txt"            :nerd "" :emoji "📝")
    ("vtt"            :nerd "" :emoji "🔠")
    ("wav"            :nerd "" :emoji "🎶")
    ("webm"           :nerd "" :emoji "🎬")
    ("webp"           :nerd "" :emoji "🖼️")
    ("woff"           :nerd "" :emoji "🔠")
    ("woff2"          :nerd "" :emoji "🔠")
    ("wranch"         :nerd "" :emoji "🔧")
    ("xcf"            :nerd "" :emoji "🖼️")
    ("xls"            :nerd "" :emoji "📊")
    ("xlsx"           :nerd "" :emoji "📊")
    ("xml"            :nerd "󰗀" :emoji "🌐")
    ("xz"             :nerd "" :emoji "📦")
    ("yaml"           :nerd "" :emoji "⚙️")
    ("yml"            :nerd "" :emoji "⚙️")
    ("zig"            :nerd "" :emoji "⚡")
    ("zip"            :nerd "" :emoji "📦")
    ("zst"            :nerd "" :emoji "📦"))
  "Icons for specific file extensions, keyed by style.")

(defun emacs-solo/file-icon (name)
  "Look up icon for file extension NAME in `emacs-solo/file-icons'."
  (let* ((row (assoc name emacs-solo/file-icons))
         (style (cond
                 ((memq 'nerd emacs-solo-icon-modules) :nerd)
                 ((string= (getenv "TERM") "xterm-kitty") :noicons)
                 (t :emoji)))
         (val (plist-get (cdr row) style)))
    (if (and val (char-displayable-p (string-to-char val)))
        val "")))

(provide 'emacs-solo-icons)
;;; emacs-solo-icons.el ends here
